# orca_alerts.py
# A comprehensive database of Orca security alert categories and names.

ORCA_ALERT_CATEGORIES = {
    "IAM misconfigurations": [
        "User with an Administrative Primitive Role (Owner/Editor)",
        "Service Account with an Administrative Primitive Role (Owner/Editor)",
        "Service Account with Admin privileges",
        "Instance Profile with Administrative Privileges",
        "IAM User with Administrative Privileges",
        "Internet-Facing Ec2 Instance Has Full Access to S3",
        "Role Can be Assumed by External Identity",
        "User with admin access to Google Storage",
        "Gcp Iam Service Account with admin access to Google Storage",
        "Lambda function shares its IAM role",
        "AD system-assigned identity is not assigned to app service",
        "Unused role with policy found",
        "Unused AWS service-linked role with policy found",
        "Role with Unused Service Access",
        "Group with Unused Service Access",
        "Unused IAM Group",
        "IAM Role Recently Used by an External Identity",
        "EC2 Instance with Administrator Privileges",
        "User with an admin/data owner/data editor access to BigQuery",
        "AWS Guard Duty: EKS Cluster with PrivilegeEscalation:Kubernetes/PrivilegedContainer",
        "User with Administrative Privileges within Resource Scope",
        "Unused AWS user's credentials",
        "User with Unused Service Access",
        "User with admin access to Pub/Sub",
        "AWS EC2 instance without IAM roles",
        "Service Account with Administrative Privileges within Resource Scope",
    ],
    "Vulnerabilities": [
        "Service Vulnerability",
        "Vulnerable Software",
        "Web-service unpatched",
        "Remote Code Execution vulnerability discovered in Apache Tomcat (CVE-2025-24813)",
        "Spring4Shell Remote Code Execution Vulnerability (CVE-2022-22965)",
        "Elevation of Privilege vulnerability found in Windows Error Reporting Service (CVE-2023-36874)",
        "Remote Code Execution vulnerability discovered in Erlang/OTP (CVE-2025-32433)",
        "Local Privilege Escalation vulnerability found in Ubuntu kernel (CVE-2023-32629)",
        "Heap Buffer Overflow Vulnerability found in cURL and libcurl (CVE-2023-38545)",
        "Remote Code Execution Vulnerability found in Exim mail transfer agent (CVE-2023-42115)",
        "Arbitrary File Read Vulnerability found in Jenkins (CVE-2024-23897)",
        "Privilege Escalation vulnerability found in the Linux Kernel (CVE-2023-3269)",
        "Apache Log4j Denial of Service Vulnerability (CVE-2021-45105)",
        "A Critical Privilege Escalation Design Flaw discovered in Google Cloud enables a Supply Chain Attack",
        "Microsoft Azure Kubernetes Service vulnerable to elevation of privilege (CVE-2023-29332)",
        "PrintNightmare Remote Code Execution Vulnerability (CVE-2021-34527)",
        "Remote Code Execution Vulnerability found in the Microsoft Windows OLE component (CVE-2023-29325)",
        "Apache Log4j Remote Code Execution Vulnerability (CVE-2021-45046)",
        "Apache Log4j Remote Code Execution Vulnerability (CVE-2021-44228)",
        "SSL/TLS Certificate is Vulnerable to Heartbleed",
        "Use-After-Free memory corruption vulnerability found in AMD Zen 2 processors (CVE-2023-20593)",
        "Account Takeover vulnerability found in Grafana (CVE-2023-3128)",
        "Compute Instance with Vulnerable Open Management Infrastructure Installed",
    ],
    "Data protection": [
        "S3 Bucket Allows Public READ Access",
        "Sensitive info in Git Repository",
        "SNS topic policy allows everyone to publish",
        "SNS topic policy allows everyone to subscribe",
        "AWS S3 bucket has global view ACL permissions enabled",
        "Lambda Function is exposed to public",
        "S3 Bucket Allows Public READ_ACP Access",
        "Azure storage container is publicly accessible",
        "Azure Storage account's Customer-Managed Keys encryption is disabled",
        "Azure Storage Account without private endpoint, subnet, or firewall configured",
        "Azure Storage account not using customer-Managed Keys encryption for Queue service",
        "Azure Storage Account file share without the latest SMB protocol version or channel encryption",
        "Azure Storage Account without immutability policy for Azure Blob Storage",
        "EBS volume unencrypted",
        "Azure Storage Account allows public access to blob containers",
        "API Gateway is publicly accessible",
        "Key Vault is unrecoverable",
        "EBS unencrypted attached volume",
        "CloudFront distribution has field-level encryption disabled",
        "Attached managed disk is not encrypted with CMK.",
        "Azure storage account is not using TLS 1.2 version",
        "CloudFront distributions origin access control is disabled",
        "Azure Storage Account allows cross tenant replication",
        "EBS snapshot is shared with AWS accounts",
        "S3 bucket data is not protected",
        "EBS Volume with unencrypted Snapshots",
        "RDS database snapshot is shared with AWS accounts",
        "CloudFront distributions default root object is not configured",
        "S3 Bucket Policy allows cross account access",
        "CloudFront distributions origin access identity is disabled",
        "S3 access control lists (ACLs) should not be used to manage user access to buckets",
        "AWS S3 Bucket Without 'MFA Delete' Enabled",
        "S3 Bucket Policy allows unknown cross account access",
        "EBS snapshot is shared with unknown AWS accounts",
        "S3 Bucket Object Versioning not Enabled",
        "IAM inline policies allow decryption on all KMS keys",
        "Cosmos DB Accounts metadata is accessible via SDK (Key-based)",
        "EC2 Instance is using an unencrypted volume",
        "S3 bucket policy allows any action from all principles",
        "Elasticsearch unrestricted access",
        "SQS queue doesn't have Dead Letter Queue configured.",
        "User managed service accounts with user-managed keys",
        "SQS queue is not encrypted at rest",
        "S3 Bucket Allows Public GET",
        "Connecting to Azure Storage account using SFTP is disabled",
        "SNS topic with public access",
        "Vm uses managed disk which is not encrypted with CMK.",
        "SNS topics are not encrypted at rest using AWS KMS",
        "SNS topic does not have an active subscription to Simple Queue Service (SQS)",
        "AWS ECR repository is publicly accessible",
        "API Gateway REST API with stages that have cache data enabled but cache is not encrypted",
        "Azure Container Registry with Unrestricted Network Access",
        "Cosmos DB Accounts Unrestricted Network Access",
        "Redshift database encryption disabled",
    ],
    "Data at risk": [
        "Sensitive data found - Google API key",
        "Potentially Personal Identifying Information found - Email Addresses",
        "Sensitive data found - Slack webhook",
        "Sensitive data found - Github OAuth 2.0 ID",
        "Sensitive data found - Slack access token",
        "Sensitive data found - MailChimp API key",
        "Sensitive data found - Stripe API key",
        "Sensitive data found - Azure Storage Account Shared Access Signature",
        "Database Table with Sensitive Data information found",
        "Database Table with Potentially Personal Identifying Information found - Credit Card Numbers",
        "Potentially Personal Identifying Information found - Social Security Numbers",
        "Database Table with Potentially Personal Identifying Information found - Personal Information",
        "Sensitive data found - Google (GCP) service account access key",
        "Sensitive data found - SendGrid API key",
        "Sensitive data found - LinkedIn secret key",
    ],
    "Lateral movement": [
        "Lambda function environment variables expose secrets",
        "Lambda Function with Admin Privileges",
        "User Privilege Escalation - Authentication Key Management (Project Scope)",
        "Privileged Role - Policy Attachment",
        "Privileged Role - User Management",
        "Privileged Role - Group Management",
        "Privileged Group - Pass Role",
        "Privileged Role - Assume Role",
        "Privileged Role - Policy Version",
        "Insecure SSH Key Pair Detected",
        "Insecure SSH Private Key Detected",
        "Privileged User - Assume Role",
        "Privileged Instance Profile - Assume Role",
        "Privileged User - Group Management",
        "Password in shell history",
        "Sensitive AWS keys on system",
        "User Privilege Escalation - Impersonation (Project Scope)",
        "Privileged Instance Profile - Policy Attachment",
        "Privileged Instance Profile - User Management",
        "Privileged Group - Assume Role",
        "Privileged Instance Profile - Group Management",
        "Privileged Instance Profile - Policy Version",
        "Privileged Instance Profile - Pass Role",
        "User Privilege Escalation - Service Update (Project Scope)",
        "Data factory global parameters expose secrets",
        "EC2 Instance with secrets in UserData Attribute",
        "User Privilege Escalation - Service Creation (Project Scope)",
        "Lambda Function exposes AWS Secret",
        "Service Account Privilege Escalation - Service Creation (Project Scope)",
        "Service Account Privilege Escalation - Impersonation (Project Scope)",
        "Privileged User - Policy Attachment",
        "Service Account Privilege Escalation - Service Update (Project Scope)",
        "Privileged Managed Policy - Policy Attachment",
        "AWS Systems Manager Parameter Exposes Secret",
        "Privileged Managed Policy - Pass Role",
        "Privileged Managed Policy - Assume Role",
        "Privileged Managed Policy - Policy Version",
        "Privileged Managed Policy - User Management",
        "Privileged Managed Policy - Group Management",
        "Privileged User - Policy Version",
        "Privileged Group - Policy Attachment",
        "Privileged Group - Policy Version",
        "Privileged Group - Pass Role",
        "Compute Instance with Permissive Service Account",
        "Group Policy Preferences with cpassword",
        "AWS Systems Manager Parameter Exposes AWS Secret",
    ],
    "Workload misconfigurations": [
        "PyPi package potentially vulnerable to dependency confusion attack",
        "NPM package potentially vulnerable to dependency confusion attack",
        "RDS database instance is not using the latest engine version",
        "RDS database cluster is not using the latest engine version",
        "Docker container escape",
        "FTP configuration with anonymous login enabled",
        "RDS database instance is using an unsupported engine version",
        "Unnecessary Service Found on Windows VM",
        "Apache Spark configuration without encryption",
        "Apache Spark configuration without authentication",
        "Insecure Executable",
        "Insecure directory permission",
        "RDS database instance has automated backups disabled",
    ],
    "Suspicious activity": [
        "AWS Guard Duty: User with Discovery:IAMUser/AnomalousBehavior",
        "AWS Guard Duty: User with Persistence:IAMUser/AnomalousBehavior",
        "AWS Guard Duty: User with CredentialAccess:IAMUser/AnomalousBehavior",
        "AWS Guard Duty: User with Impact:IAMUser/AnomalousBehavior",
        "AWS Guard Duty: Ec2 with DefenseEvasion:EC2/UnusualDNSResolver",
        "AWS Guard Duty: S3 Bucket with Policy:S3/BucketAnonymousAccessGranted",
        "A security alert was triggered on your SQL Server by Microsoft Defender",
        "AWS Guard Duty: S3 Bucket with Policy:S3/BucketBlockPublicAccessDisabled",
        "CloudTrail trail logging was stopped",
        "AWS Guard Duty: Ec2 with Recon:EC2/PortProbeUnprotectedPort",
        "AWS Guard Duty: RDS instance with CredentialAccess:RDS/AnomalousBehavior.SuccessfulLogin",
        "AWS Guard Duty: Ec2 with Impact:EC2/WinRMBruteForce",
        "AWS Guard Duty: Ec2 with UnauthorizedAccess:EC2/SSHBruteForce",
        "AWS Guard Duty: User with Discovery:IAMUser/AnomalousBehavior",
        "A security alert was triggered on your SQL DB by Microsoft Defender",
        "AWS Guard Duty: Ec2 with Recon:EC2/Portscan",
        "AWS Guard Duty: EC2 with suspicious traffic from an instance with a database service or sensitive personally identifiable information (PII)",
        "AWS Guard Duty: Ec2 with Behavior:EC2/NetworkPortUnusual",
    ],
    "Network misconfigurations": [
        "EKS security group allows incoming traffic on forbidden ports",
        "Network ACL Allow Inbound Traffic from All Ports",
        "Network ACL Allows all Inbound ICMP IPv4 Traffic",
        "Network ACL Allows all Inbound Traffic",
        "Ensure no Network ACLs allow ingress from 0.0.0.0/0 to SSH port (22)",
        "Ensure no Network ACLs allow ingress from 0.0.0.0/0 to Remote Desktop port (3389)",
        "default network access rule for Storage Accounts is not set to deny",
        "VPC Endpoint Publicly Exposed",
        "WebApp Non-HTTPS Run allowed",
        "RDS database instance is using default ports",
        "Ensure the default security group of every VPC restricts all traffic",
        "Storage account insecure transfer",
        "RDS DB cluster is using default ports",
        "Security group allows inbound to a large port range",
        "Elastic Load Balancer (ELBV2) with public access",
        "WebApp unsecure FTP Deployment Enabled",
        "Security group allows unrestricted inbound traffic",
        "Security group allows egress to predefined blocked ports",
        "Security group allows inbound access from uncommon ports",
        "Azure Function App unsecure FTP Deployment Enabled",
        "Ec2 instance with public IPv4 address",
        "EKS Kubernetes API server publicly accessible",
        "Network ACL Allow all Outbound Traffic",
        "Network ACL Allow Outbound Traffic to All Ports",
        "Azure SQL Server Firewall allows access from all Azure Services",
        "Network security group rule allows unrestricted incoming access from the Internet",
        "Classic Load Balancer (ELB) with public access",
        "Security group allows inbound access from high risk ports",
        "VPC NACL allows ingress traffic from blocked ports",
        "AWS Ec2 security group allows unrestricted ICMP traffic from the Internet",
        "Azure Cosmos DB firewall allows access from all public Azure datacenters",
        "Security group allows inbound access to http ports",
        "Azure virtual machine is publicly accessible",
        "Security group allows inbound access to TCP port 22 (SSH)",
        "Security group allows inbound access to TCP port 443 (HTTPS)",
        "ElastiCache Memcached Cluster with Default Port",
        "Network security group rule allows direct HTTP/S access from the Internet",
        "Azure Cache for Redis public network access is enabled",
        "Network ACL allows ingress from 0.0.0.0/0 to SSH port (22) or Remote Desktop port (3389)",
        "Security group allows inbound access from unauthorized ports",
        "Azure basic Load Balancer with public IP",
        "Security group allows inbound access to TCP and UDP port 53 (DNS)",
        "Default security group allows inbound unrestricted traffic",
        "Network ACL Allows all Inbound ICMP IPv6 Traffic",
        "Security group allows inbound access to TCP port 3389 (RDP)",
        "Security group allows inbound access to TCP port 3306 (MYSQL)",
        "Network security group rule allows direct SSH access from the internet",
        "Security group allows inbound access to TCP port 9200 or port 9300 (Elasticsearch)",
        "AKS Kubernetes API server publicly accessible",
    ],
    "Neglected assets": [
        "Unsupported Host OS",
        "Unpatched OS",
        "Lambda function runtime outdated",
        "WebApp HTTP version outdated",
        "FunctionApp Python Framework outdated",
        "Subdomain is under risk of a takeover",
        "Azure App Service is not using the latest TLS version",
        "Domain expired",
        "Unsupported Kubernetes version is installed on Azure AKS cluster",
        "Expired SSL Certificate for a Subdomain",
        "Route53 Alias Record Pointing to Invalid Resource",
        "Outdated AMI for ECS-related instance",
        "Domain's expiration date is in less than 30 days",
        "Unused ELBv2",
        "Expired TLS/SSL Certificates in IAM Certificate Manager",
        "User with Unused Credentials",
        "Cloud function runtime outdated",
        "Azure Application Gateway frontend configuration without routing rules",
        "Elbv2 listener expired ACM certificate",
        "SSL/TLS Certificate's will expire in 30 days",
        "Azure Load balancer without associated backend pools",
        "Azure Load balancer without load balancing rules",
        "Amazon MQ broker doesn't have the latest engine version",
        "Expired SSL Certificate",
        "Host OS reaching End of Support",
    ],
    "Authentication": [
        "App Service Authentication is off",
        "WebApp Client Certification not required",
        "Azure Function App Client Certification is not required",
        "SSH Authentication with username and password",
        "SSH login permitted for root",
        "Access Keys Rotation (90 days)",
        "Unused Credentials Found - over 45 days",
        "Unused Credentials Found - over 90 days",
        "Weak Os Password",
        "Event bus allow cross account access",
        "Service account key was not rotated in over 90 days",
        "Unauthenticated exposed tool with sensitive data",
        "RDS database instance is using the default master username",
        "Redshift using default port",
        "User with disabled MFA",
        "Password Policy does not Enforce Proper Minimum Length",
        "API key is not restricted to trusted hosts or apps",
        "API key is not restricted to APIs",
        "Password policy doesn't expire passwords in 90 days",
        "Password policy without password expiration period",
        "Cross-Account Access Without External ID or MFA",
        "Password policy does not require symbols",
        "Password policy does not require uppercase characters",
        "Password policy does not meet PCI DSS",
        "Password policy does not require lowercase characters",
        "API Gateway Route is not configured with an authorization type",
        "Password policy does not require numbers",
        "Project with API keys",
        "User with Two Active Access Keys",
        "Azure subscription without resource lock administrator custom role",
        "Ensure a Custom Role is Assigned Permissions for Administering Resource Locks",
        "Non Corporate Authentication Key",
        "RDS database cluster is using the default master username",
        "Azure Container registry with ARM audience tokens authentication enabled",
        "VM instance with 'Block Project-wide SSH keys' disabled",
        "Weak Encryption Key",
        "RDS Cluster IAM authentication disabled",
        "Password Policy does not Prevent Password Reuse",
        "Users are being created with Access Keys during initial setup",
    ],
    "Logging and monitoring": [
        "Storage classic logging is not enabled for all logging Blob service - read, write, and delete requests",
        "Storage classic logging is not enabled for all logging Queue service - read, write, and delete requests",
        "Enhanced instance metadata service (IMDSv2) is not enforced",
        "Lambda function with disabled tracing",
        "Lambda function without log group",
        "Web server configuration with insufficient monitoring",
        "Azure Application Insights isn't enabled on your Function App",
        "Metric and alarm do not exist for S3 configuration changes",
        "Storage Bucket Logging is Disabled",
        "No monitoring for VPC network changes",
        "No monitoring for VPC Network Firewall rule changes",
        "No monitoring for VPC network route changes",
        "No monitoring for Audit Configuration changes",
        "No monitoring for project ownership changes",
        "No monitoring for Custom Role changes",
        "No monitoring for SQL instance configuration changes",
        "No monitoring for Cloud Storage IAM permission changes",
        "VPC with Cloud DNS logging disabled",
        "S3 Bucket Server Access Logging is Disabled",
        "CloudTrail bucket MFA delete is disabled",
        "Azure Cache for Redis isn't configured with Diagnostic Settings",
        "Azure SQL server without desired audit action groups configured",
        "Azure ADT without email alert",
        "SQL server audit retention less than 90 days",
        "Redshift audit logging is disabled",
        "Redshift activity logging is disabled",
    ],
    "Best practices": [
        "X-Frame-Options Header Is Missing",
        "Backup vault should have a policy",
        "Nginx Web server configuration is exposed",
        "Apache Web server configuration is exposed",
        "Backup vault should be using Customer Master Keys",
        "AWS S3 bucket is not using DNS-compliant bucket name",
        "PHP Web server configuration is exposed",
        "Glue Data Catalog data-at-rest encryption without KMS CMKs",
        "DynamoDB table is not encrypted using KMS key",
        "Soft delete is disabled for blobs in azure storage account",
        "RDS database cluster snapshot is not using customer-managed KMS keys",
        "RDS database instance snapshot is not using customer-managed KMS keys",
        "Azure storage account keys are using for authorization",
        "RDS database instance is not using customer-managed KMS keys",
        "Application load balancer without invalid HTTP header drop",
        "DynamoDB table is not encrypted using customer-managed KMS key",
        "Users with Inline or Directly Attached Policies Found",
        "Kafka cluster is not using customer-managed KMS keys",
        "VM disk without Customer-Supplied Encryption Key",
        "Route 53 Domain has Privacy Protection disabled",
        "Backup vault should be configured to send notifications for each failed backup job",
        "DocumentDB cluster is not using customer-managed KMS keys",
    ],
    "Malicious activity": [
        "Administrator Created Scheduled Task On System",
        "User added to local Administrator group [filtered]",
        "Scheduled Task Created in Task Scheduler Library Root Node",
        "Scheduled Task Created On System",
        "Suspicious command in shell history",
    ],
    "Vendor services misconfigurations": [
        "Microsoft Services not excluded from Firewall",
        "EC2 launch template does not require Instance Metadata Service Version 2 (IMDSv2)",
        "ECS task definition is not configured with read-only access to root filesystem",
        "Auto Scaling group should configure EC2 instances to require Instance Metadata Service Version 2 (IMDSv2)",
        "Auto Scaling group launch configuration/template is set with metadata response hop limit greater than 1",
        "FunctionApp service plan not optimized",
        "EKS Cluster with enabled Public Endpoint or disabled Private Endpoint",
        "AWS SageMaker notebook instance is configured with an outdated minimum Instance Metadata Service Version (IMDS)",
        "'Always on' setting isn't enabled on your app service",
        "AKS cluster is not using Azure Active Directory authorization",
        "AKS is running without Azure Policy for Kubernetes clusters",
        "AKS cluster is not using a network policy plugin",
        "AKS cluster is using publicly accessible nodes",
        "AKS cluster is not using Azure Active Directory authentication",
        "Lambda Function with public access policy",
        "Cloud function with policy members 'all users'",
        "Cloud function with public invoker privileges",
        "Classic Load Balancer is not configured with defensive or strictest desync mitigation mode",
        "API Gateway has Content Encoding disabled",
        "API Gateway is not using AWS WAF",
        "CloudFront distributions logging is disabled",
        "Ec2 instance is not managed by the Systems Manager",
        "S3 Bucket not Configured with Public Access Block",
        "Ec2 Systems Manager(SSM) non compliant - patch",
        "CloudFront distributions should use custom SSL/TLS certificates",
        "RDS database instance has IAM database authentication disabled",
        "EKS Cluster without Fargate Profiles",
        "EKS Cluster secrets are not encrypted",
        "Ec2 Systems Manager(SSM) non compliant - association",
        "Azure virtual machine Trusted Launch is not enabled properly",
        "SQL Server ATP Admin not Receiving Alerts",
        "SQL server ADS and ATP are Not set to 'All'",
        "SQL server ATP are disabled",
        "Vm uses unmanaged disk.",
        "Amazon EC2 instances launched using Auto Scaling group launch configurations should not have public IP addresses",
    ]
}

# A flattened list of all alert names for easy searching
ALL_ALERTS = sorted([alert for category in ORCA_ALERT_CATEGORIES.values() for alert in category])

# A list of business units
BUSINESS_UNITS = [
    "AFC", "AFC-ALL", "AFC-COS", "AFC-CTM", "Auction Frontier", "Autoniq",
    "AutoVIN", "BLC", "CarsArrive", "CarWave", "Common Customer", "EDMM",
    "GCP", "HTL", "International", "KDS", "LaneLink", "OL NewWave", "OMP",
    "OPENLANE", "Openlane CA", "PAR", "Peoplesoft", "RDN", "Salesforce", "SAP",
    "Service Ops", "sre-encabulators", "sre-jedi", "sre-mavericks", "TDD",
    "TradeRev"
]